# fly.toml app configuration file generated for saleor-app-payment-stripe on 2024-01-28T03:37:25+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'saleor-app-payment-stripe'
primary_region = 'cdg'

[build]

[env]
  SALEOR_API_URL = 'https://saleor.fly.dev/graphql/'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
